# Generated by Django 4.0.1 on 2022-01-24 08:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=250)),
                (
                    'status',
                    models.CharField(
                        choices=[('published', 'Published'), ('unpublished', 'Unpublished')],
                        default='unpublished',
                        max_length=120,
                    ),
                ),
                ('page_url', models.CharField(blank=True, max_length=250, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_%(class)ss',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='updated_%(class)ss',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'ordering': ('order', 'id'),},
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=250)),
                (
                    'status',
                    models.CharField(
                        choices=[('published', 'Published'), ('unpublished', 'Unpublished')],
                        default='unpublished',
                        max_length=120,
                    ),
                ),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_%(class)ss',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'documents',
                    models.ManyToManyField(
                        blank=True, related_name='subsection_documents', to='attachment.FileAttachment'
                    ),
                ),
                ('roles', models.ManyToManyField(blank=True, to='auth.Group')),
                (
                    'section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='help.section'
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='updated_%(class)ss',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'ordering': ('order', 'id'),},
        ),
    ]
