# Generated by Django 4.0.1 on 2022-01-31 08:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                (
                    'content_type',
                    models.CharField(
                        choices=[
                            ('subtitle', 'Subtitle'),
                            ('text', 'Text'),
                            ('video_url', 'Video url'),
                            ('image', 'Image'),
                        ],
                        default='subtitle',
                        max_length=120,
                    ),
                ),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_%(class)ss',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'image',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='article_image',
                        to='attachment.fileattachment',
                    ),
                ),
                (
                    'subsection',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='article_content',
                        to='help.subsection',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='updated_%(class)ss',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'ordering': ('order', 'id'),},
        ),
    ]
